# Generated by Django 4.1 on 2022-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aisatsu", models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name="Asa",
        ),
    ]
